add keyboard shortcut
nogahighland/confluence-pagetree-search pull request #357
Opened 2022-04-11 04:14 UTC by sangjin-oh

- [x] add usage

<img width="742" alt="image" src="https://user-images.githubusercontent.com/47313623/162664069-f97209d6-dc1c-49ff-a191-ea3a62dade8c.png">

2022-04-11 05:38 UTC, nogahighland requested changes
use of `<kbd>` make the key look like → <kbd><kbd>cmd</kbd>+<kbd>K</kbd></kbd>
https://qiita.com/ygkn/items/0b485f6aedd15eadec33

2022-04-11 05:38 UTC, nogahighland commented on README.md
> +| Cmd + Shift + K | Enable Extension |
```suggestion
| Cmd + Shift + K (Default) | Enable Extension |
```

↑May be good, because user can change the shortcut

2022-04-11 05:38 UTC, nogahighland commented on README.md
> +| Cmd + K | Search |
```suggestion
| Cmd + K (Ctrl + space) | Search |
```

For windows user, <kbd>ctrl</kbd>+<kbd>space</kbd>. Please see the document.
https://fablic.qiita.com/kissy0601/items/ab4227a1141d9ae294fe

2022-04-18 07:03 UTC, sangjin-oh commented
> 

@kisshy0601 Thank you! I didn't know the kbd tag!

2022-05-05 07:50 UTC, nogahighland approved these changes
Thank you! LGTM

2022-05-08 23:19 UTC, merged