Bump to 3.1.4
nogahighland/confluence-pagetree-search pull request #484
Opened 2022-11-24 02:21 UTC by hiichan

Bump to 3.1.4 for libraries updates.

2022-11-24 02:25 UTC, hiichan commented
Attach zip.

[r-confluence-pagetree-search.zip](https://github.com/nogahighland/confluence-pagetree-search/files/10080340/r-confluence-pagetree-search.zip)

2022-11-24 02:32 UTC, hiichan commented
@nogahighland
Is this the right way to do it?

2022-11-24 05:00 UTC, nogahighland requested changes
# Bump `manifest.json`'s version

Please update here. 
https://github.com/nogahighland/confluence-pagetree-search/blob/fd89d5df47a2c3adef10e944d8d93f4a040e1b2d/src/manifest.json#L4

Without it, upload fails.

# Correct `JIRA_HOST`

Plus, in `index.bundle.js` correct `JIRA_HOST` doesn't seem to be set properly.
![image](https://user-images.githubusercontent.com/1780339/203695990-8b2ed5ff-b4e3-4a50-98e4-d05f723dae84.png)

Maybe you saw this section, but please replace `https://your-jira-host` for your company's JIRA host url.
https://github.com/nogahighland/confluence-pagetree-search/blob/fd89d5df47a2c3adef10e944d8d93f4a040e1b2d/README.md#L40-L43

### additional info

<details>
It may be also useful for you to read [Makefile](https://github.com/nogahighland/confluence-pagetree-search/blob/r-confluence/Makefile)

`JIRA_HOST` is used in notification button ![image](https://user-images.githubusercontent.com/1780339/203697336-d4bb6080-abc5-43c7-a094-2aa646f11c56.png)

in source code
https://github.com/nogahighland/confluence-pagetree-search/blob/fd89d5df47a2c3adef10e944d8d93f4a040e1b2d/src/components/notification-item.vue#L23-L52

This was implemented because the page's functionality doesn't work properly after enabling this extension, but to be honest, actually many other functionality don't work other than notification. If you don't feel the replaced notification is useless, please remove [NotificationWrapper](https://github.com/nogahighland/confluence-pagetree-search/blob/r-confluence/src/components/notification-wrapper.vue) and its implemented places.
</details>

2022-11-24 05:00 UTC, nogahighland commented on README.md
> +3.1.4| Security Updates
#484 would be better 👍

2022-11-24 05:09 UTC, hiichan commented on README.md
> +3.1.4| Security Updates
I fixed it.

2022-11-24 05:16 UTC, hiichan commented
@nogahighland 
I re-built the zip.
Could I get your re-review?

[r-confluence-pagetree-search.zip](https://github.com/nogahighland/confluence-pagetree-search/files/10080989/r-confluence-pagetree-search.zip)

2022-11-24 06:00 UTC, nogahighland commented
@hiichan 
Thanks! Packaging seems fine.
I checked out your branch and tried if it works, but it doesn't work. Please check if it works on your environment.

What I did:

```sh
$ JIRA_HOST='https://your-jira-host' make serve
```

https://github.com/nogahighland/confluence-pagetree-search/blob/0370382515c7408b16b897e24890a423e144d162/README.md#L51-L52

Error log in the Chrome inspector:

```
index.bundle.js:226075 [Vue warn]: Unknown custom element: <font-awesome-icon> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

found in

---> <NotificationWrapper> at src/components/notification-wrapper.vue
       <Root>
```

Diff between the previous version `r-confluence-v3.1.3` and suspicious diff

```sh
$ git diff r-confluence-v3.1.3
...
-    "@fortawesome/vue-fontawesome": "^2.0.8",
+    "@fortawesome/vue-fontawesome": "^2.0.9",
...
```

<details><summary>Whole diff</summary>
```diff
diff --git a/README.md b/README.md
index 4299b64..f42c777 100644
--- a/README.md
+++ b/README.md
@@ -89,4 +89,5 @@ version|description
 3.1.0| #339
 3.1.1| Security Updates
 3.1.2| #446
-3.2.3| #447
+3.1.3| #447
+3.1.4| #484
diff --git a/package.json b/package.json
index 44fceab..9743d95 100644
--- a/package.json
+++ b/package.json
@@ -1,6 +1,6 @@
 {
   "name": "r-confluence-pagetree-search",
-  "version": "3.1.3",
+  "version": "3.1.4",
   "main": "index.js",
   "license": "MIT",
   "scripts": {
@@ -8,7 +8,7 @@
     "test": "jest"
   },
   "devDependencies": {
-    "@types/chrome": "^0.0.197",
+    "@types/chrome": "^0.0.203",
     "@types/copy-webpack-plugin": "^10.1.0",
     "@types/faker": "^5.5.9",
     "@types/jest": "^27.5.0",
@@ -18,7 +18,7 @@
     "@vue/eslint-config-typescript": "^7.0.0",
     "axios": "^0.27.2",
     "copy-webpack-plugin": "^11.0.0",
-    "css-loader": "^6.7.1",
+    "css-loader": "^6.7.2",
     "eslint": "^7.32.0",
     "eslint-config-airbnb-base": "^15.0.0",
     "eslint-config-prettier": "^8.5.0",
@@ -27,21 +27,21 @@
     "eslint-plugin-prettier": "^4.2.1",
     "eslint-plugin-vue": "^7.20.0",
     "jest": "^27.5.1",
-    "jest-junit": "^14.0.1",
-    "node-sass": "^7.0.3",
+    "jest-junit": "^15.0.0",
+    "node-sass": "^8.0.0",
     "prettier-eslint-cli": "^5.0.1",
     "pug": "^3.0.2",
     "pug-plain-loader": "^1.1.0",
-    "sass-loader": "^13.0.2",
+    "sass-loader": "^13.2.0",
     "ts-jest": "^27.1.4",
     "ts-loader": "^9.4.1",
     "ts-node": "^10.9.1",
     "typescript": "^4.7.4",
-    "vue": "^2.7.10",
+    "vue": "^2.7.13",
     "vue-loader": "^15.9.8",
-    "vue-template-compiler": "^2.7.10",
-    "webpack": "^5.74.0",
-    "webpack-cli": "^4.10.0"
+    "vue-template-compiler": "^2.7.13",
+    "webpack": "^5.75.0",
+    "webpack-cli": "^5.0.0"
   },
   "volta": {
     "node": "14.17.6",
@@ -50,9 +50,9 @@
   "dependencies": {
     "@fortawesome/fontawesome-svg-core": "^1.2.36",
     "@fortawesome/free-solid-svg-icons": "^5.15.4",
-    "@fortawesome/vue-fontawesome": "^2.0.8",
+    "@fortawesome/vue-fontawesome": "^2.0.9",
     "@types/fast-levenshtein": "^0.0.2",
-    "@types/lodash": "^4.14.186",
+    "@types/lodash": "^4.14.190",
     "@types/moment": "^2.13.0",
     "faker": "^5.5.3",
     "fast-levenshtein": "^3.0.0",
diff --git a/src/manifest.json b/src/manifest.json
index 7102e07..2061648 100644
--- a/src/manifest.json
+++ b/src/manifest.json
@@ -1,7 +1,7 @@
 {
   "manifest_version": 3,
   "name": "R-Confluence Pagetree Search",
-  "version": "3.1.3",
+  "version": "3.1.4",
   "description": "Add a feature to search page tree by its name.",
   "content_security_policy": {
     "extension_pages": "default-src 'none'; script-src 'self'; connect-src 'self'; img-src 'self'; style-src 'self';base-uri 'self';form-action 'self'"
diff --git a/yarn.lock b/yarn.lock
index 38fef20..755da8b 100644
--- a/yarn.lock
+++ b/yarn.lock
@@ -543,16 +543,21 @@
   dependencies:
     "@fortawesome/fontawesome-common-types" "^0.2.36"
 
-"@fortawesome/vue-fontawesome@^2.0.8":
-  version "2.0.8"
-  resolved "https://registry.yarnpkg.com/@fortawesome/vue-fontawesome/-/vue-fontawesome-2.0.8.tgz#9c9ae1cd2cbe7f4b0c63dd53709c26167d541aa6"
-  integrity sha512-SRmP0q9Ox4zq8ydDR/hrH+23TVU1bdwYVnugLVaAIwklOHbf56gx6JUGlwES7zjuNYqzKgl8e39iYf6ph8qSQw==
+"@fortawesome/vue-fontawesome@^2.0.9":
+  version "2.0.9"
+  resolved "https://registry.yarnpkg.com/@fortawesome/vue-fontawesome/-/vue-fontawesome-2.0.9.tgz#7df35818135be54fd87568f16ec7b998a3d0cce8"
+  integrity sha512-tUmO92PFHbLOplitjHNBVGMJm6S57vp16tBXJVPKSI/6CfjrgLycqKxEpC6f7qsOqUdoXs5nIv4HLUfrOMHzuw==
 
 "@gar/promisify@^1.0.1":
   version "1.1.2"
   resolved "https://registry.yarnpkg.com/@gar/promisify/-/promisify-1.1.2.tgz#30aa825f11d438671d585bd44e7fd564535fc210"
   integrity sha512-82cpyJyKRoQoRi+14ibCeGPu0CwypgtBAdBhq1WfvagpCZNKqwXbKwXllYSMG91DhmG4jt9gN8eP6lGOtozuaw==
 
+"@gar/promisify@^1.1.3":
+  version "1.1.3"
+  resolved "https://registry.yarnpkg.com/@gar/promisify/-/promisify-1.1.3.tgz#555193ab2e3bb3b6adc3d551c9c030d9e860daf6"
+  integrity sha512-k2Ty1JcVojjJFwrg/ThKi2ujJ7XNLYaFGNB/bWT9wGR+oSMJHMa5w+CUq6p/pVrKeNNgA7pCqEcjSnHVoqJQFw==
+
 "@humanwhocodes/config-array@^0.5.0":
   version "0.5.0"
   resolved "https://registry.yarnpkg.com/@humanwhocodes/config-array/-/config-array-0.5.0.tgz#1407967d4c6eecd7388f83acf1eaf4d0c6e58ef9"
@@ -799,6 +804,14 @@
     "@gar/promisify" "^1.0.1"
     semver "^7.3.5"
 
+"@npmcli/fs@^2.1.0":
+  version "2.1.2"
+  resolved "https://registry.yarnpkg.com/@npmcli/fs/-/fs-2.1.2.tgz#a9e2541a4a2fec2e69c29b35e6060973da79b865"
+  integrity sha512-yOJKRvohFOaLqipNtwYB9WugyZKhC/DZC4VYPmpaCzDBrA8YpK3qHZ8/HGscMnE4GqbkLNuVcCnxkeQEdGt6LQ==
+  dependencies:
+    "@gar/promisify" "^1.1.3"
+    semver "^7.3.5"
+
 "@npmcli/move-file@^1.0.1":
   version "1.1.2"
   resolved "https://registry.yarnpkg.com/@npmcli/move-file/-/move-file-1.1.2.tgz#1a82c3e372f7cae9253eb66d72543d6b8685c674"
@@ -807,6 +820,14 @@
     mkdirp "^1.0.4"
     rimraf "^3.0.2"
 
+"@npmcli/move-file@^2.0.0":
+  version "2.0.1"
+  resolved "https://registry.yarnpkg.com/@npmcli/move-file/-/move-file-2.0.1.tgz#26f6bdc379d87f75e55739bab89db525b06100e4"
+  integrity sha512-mJd2Z5TjYWq/ttPLLGqArdtnC74J6bOzg4rMDnN+p1xTacZ2yPRCk2y0oSWQtygLR9YVQXgOcONrwtnk3JupxQ==
+  dependencies:
+    mkdirp "^1.0.4"
+    rimraf "^3.0.2"
+
 "@sinonjs/commons@^1.7.0":
   version "1.8.3"
   resolved "https://registry.yarnpkg.com/@sinonjs/commons/-/commons-1.8.3.tgz#3802ddd21a50a949b6721ddd72da36e67e7f1b2d"
@@ -826,6 +847,11 @@
   resolved "https://registry.yarnpkg.com/@tootallnate/once/-/once-1.1.2.tgz#ccb91445360179a04e7fe6aff78c00ffc1eeaf82"
   integrity sha512-RbzJvlNzmRq5c3O09UipeuXno4tA1FE6ikOjxZK0tuxVv3412l64l5t1W5pj4+rJq9vpkm/kwiR07aZXnsKPxw==
 
+"@tootallnate/once@2":
+  version "2.0.0"
+  resolved "https://registry.yarnpkg.com/@tootallnate/once/-/once-2.0.0.tgz#f544a148d3ab35801c1f633a7441fd87c2e484bf"
+  integrity sha512-XCuKFP5PS55gnMVu3dty8KPatLqUoy/ZYzDzAGCQ8JNFCkLXzmI7vNHCR+XpbZaMWQK/vQubr7PkYq8g470J/A==
+
 "@tsconfig/node10@^1.0.7":
   version "1.0.8"
   resolved "https://registry.yarnpkg.com/@tsconfig/node10/-/node10-1.0.8.tgz#c1e4e80d6f964fbecb3359c43bd48b40f7cadad9"
@@ -879,10 +905,10 @@
   dependencies:
     "@babel/types" "^7.3.0"
 
-"@types/chrome@^0.0.197":
-  version "0.0.197"
-  resolved "https://registry.yarnpkg.com/@types/chrome/-/chrome-0.0.197.tgz#c1b50cdb72ee40f9bc1411506031a9f8a925ab35"
-  integrity sha512-m1NfS5bOjaypyqQfaX6CxmJodZVcvj5+Mt/K94EBHkflYjPNmXHAzbxfifdLMa0YM3PDyOxohoTS5ug/e6p5jA==
+"@types/chrome@^0.0.203":
+  version "0.0.203"
+  resolved "https://registry.yarnpkg.com/@types/chrome/-/chrome-0.0.203.tgz#cf883669ba489ec965e48d32cdcf14f45437f7cf"
+  integrity sha512-JlQNebwpBETVc8U1Rr2inDFuOTtn0lahRAhnddx1dd0S5RrLAFJEEsyIu7AXI14mkCgSunksnuLGioH8kvBqRA==
   dependencies:
     "@types/filesystem" "*"
     "@types/har-format" "*"
@@ -991,10 +1017,10 @@
   resolved "https://registry.yarnpkg.com/@types/json5/-/json5-0.0.29.tgz#ee28707ae94e11d2b827bcbe52 [...]

2022-12-11 14:09 UTC, nogahighland commented
@hiichan 
Any updates?

2022-12-12 00:23 UTC, hiichan commented
I tried to change version of some packages to previous version, but it didn't resolve this problem.
So I need some time.

Do you have any solution?

2022-12-12 14:46 UTC, nogahighland commented
@hiichan 
You mean, you downgraded the below package and related ones too?
```
"@fortawesome/vue-fontawesome": "^2.0.8"
```
Unfortunately I don't have an idea because I don't have an environment to reproduce the bug.

2022-12-14 03:17 UTC, hiichan commented
Yes, I tried it.

I think, to resolve this problem, I need time.
So I will try it when I have a time. m(__)m

2026-04-09 02:24 UTC, closed without merging